env:
  browser: true
  es2018: true
  greasemonkey: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  max-depth:
    - warn
    - 3
  quotes:
    - warn
    - single
  semi:
    - error
    - always

  comma-dangle:
    - error
    - always-multiline
  operator-assignment:
    - error
    - always
  quote-props:
    - error
    - as-needed

  eqeqeq:
    - error
    - always
  strict:
    - error
    - function
  yoda:
    - error
    - never

  consistent-return: error
  require-unicode-regexp: error

  prefer-const: warn
  prefer-template: warn

  no-bitwise: error
  no-confusing-arrow: error
  no-else-return: error
  no-eq-null: error
  no-eval: error
  no-lonely-if: error
  no-shadow: error
  no-unneeded-ternary: error
  no-useless-concat: error
  no-useless-return: error
  no-var: error
