parserOptions:
  ecmaVersion: 2018
env:
  browser: true
  greasemonkey: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always
  no-else-return: error
  no-useless-return: error
  no-lonely-if: error
  no-var: error

