parserOptions:
  ecmaVersion: 2018
env:
  browser: true
  greasemonkey: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always

  no-confusing-arrow: error
  no-else-return: error
  no-eq-null: error
  no-lonely-if: error
  no-shadow: error
  no-unneeded-ternary: error
  no-useless-concat: error
  no-useless-return: error
  no-var: error
