version: 2.1

jobs:
  lint:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - restore_cache:
          key: eslint-alpine
      - run:
          name: Install ESLint
          command: npm install eslint
      - save_cache:
          paths:
            - ./node_modules
            - ./package-lock.json
          key: eslint-alpine-{{ checksum "./package-lock.json" }}
      - run:
          name: OS release
          command: cat /etc/os-release
      - run:
          name: Node.js version
          command: node --version
      - run:
          name: ESLint version
          command: npx eslint --version
      - run:
          name: Run ESLint
          command: npx eslint -- ./*.js

workflows:
  lint:
    jobs:
      - lint
