version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install ESLint
          command: npm install --global eslint
      - run:
          name: System information
          command: uname -a
      - run:
          name: Node.js version
          command: node --version
      - run:
          name: Run ESLint
          command: eslint ./*.js
