version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: eslint-application
      - run:
          name: Install ESLint
          command: npm install eslint
      - save_cache:
          paths:
            - ./node_modules
            - ./package-lock.json
          key: eslint-application-{{ checksum "./package-lock.json" }}
      - run:
          name: OS release
          command: cat /etc/debian_version
      - run:
          name: Kernel version
          command: uname -a
      - run:
          name: Node.js version
          command: node --version
      - run:
          name: ESLint version
          command: ./node_modules/.bin/eslint --version
      - run:
          name: Run ESLint
          command: ./node_modules/.bin/eslint -- ./*.js
